### ISSUE TITLE
Event-driven corotines

### ISSUE THREAD

**Issue by ameaninglessname** [landelare/ue5coro#10]
It looks like in current implementation, most of the coroutines are tick based.

I want to use a custom Scheduler to schedule these awaited awaiter objects, would this usage planed to be supported?

If not, I guess i need to extend the awaiter types and related stuff;)

**Comment by landelare** [comment]
Nothing like this is planned. If you want to use your own scheduler, you'll need to implement your own coroutine promise. The engine has an experimental coroutine plugin that you might find useful.
