### ISSUE TITLE
failed to compile "DoTests" in file DelegateAwaiterTest.cpp

### ISSUE THREAD

**Issue by ameaninglessname** [landelare/ue5coro#13]
```c++
template<int N, typename... T>
void DoTests(FAutomationTestBase& Test)
{
	if constexpr (N < 8)
	{
		DoTest<(N & 4) != 0, (N & 2) != 0, (N & 1) != 0, T...>(Test);
		DoTests<N + 1, T...>(Test);
	}
}
```

![image](https://github.com/landelare/ue5coro/assets/20263103/4c7a9640-4ee1-4315-8d69-2b22276ecffc)

<details>
<summary markdown="span">Text</summary>
  utility(538): [C2338] static_assert failed: 'tuple index out of bounds'
  AsyncAwaiters.h(249): [C2338] see reference to class template instantiation 'std::tuple_element<18446744073709551615,std::tuple<>>' being compiled
  AsyncAwaiters.h(249): [C2338] see reference to alias template instantiation 'std::tuple_element_t<18446744073709551615,std::tuple<>>' being compiled
  AsyncAwaiters.h(257): [C2338] see reference to alias template instantiation 'UE5Coro::Private::TDecayedPayload<>::TType<18446744073709551615>' being compiled
  AsyncAwaiters.h(344): [C2338] see reference to class template instantiation 'UE5Coro::Private::TDecayedPayload<>' being compiled
  AsyncAwaiters.h(221): [C2338] see reference to function template instantiation 'UE5Coro::Private::TDynamicDelegateAwaiter<R>::TDynamicDelegateAwaiter<T>(T &)' being compiled
  AsyncAwaiters.h(221): [C2338] see reference to function template instantiation 'UE5Coro::Private::TDynamicDelegateAwaiter<R>::TDynamicDelegateAwaiter<T>(T &)' being compiled
  AsyncAwaiters.h(221): [C2338] while compiling class template member function 'UE5Coro::Private::TDynamicDelegateAwaiter<R> UE5Coro::Private::TAwaitTransform<UE5Coro::Private::FAsyncPromise,FUE5CoroTestDynamicVoidDelegate,void>::operator ()(T &)'
  AsyncCoroutine.h(259): [C2338] see reference to function template instantiation 'UE5Coro::Private::TDynamicDelegateAwaiter<R> UE5Coro::Private::TAwaitTransform<UE5Coro::Private::FAsyncPromise,FUE5CoroTestDynamicVoidDelegate,void>::operator ()(T &)' being compiled
  AsyncCoroutine.h(257): [C2338] see reference to class template instantiation 'UE5Coro::Private::TAwaitTransform<UE5Coro::Private::FAsyncPromise,FUE5CoroTestDynamicVoidDelegate,void>' being compiled
  DelegateAwaiterTest.cpp(104): [C2338] see reference to function template instantiation 'UE5Coro::Private::TDynamicDelegateAwaiter<R> UE5Coro::Private::FAsyncPromise::await_transform<`anonymous-namespace'::TSelect<true,false>::FVoid&>(T)' being compiled
  DelegateAwaiterTest.cpp(277): [C2338] see reference to function template instantiation 'void `anonymous-namespace'::DoTest<true,false,false,>(FAutomationTestBase &)' being compiled
  DelegateAwaiterTest.cpp(277): [C2338] see reference to function template instantiation 'void `anonymous-namespace'::DoTests<4,>(FAutomationTestBase &)' being compiled
  DelegateAwaiterTest.cpp(277): [C2338] see reference to function template instantiation 'void `anonymous-namespace'::DoTests<3,>(FAutomationTestBase &)' being compiled
  DelegateAwaiterTest.cpp(277): [C2338] see reference to function template instantiation 'void `anonymous-namespace'::DoTests<2,>(FAutomationTestBase &)' being compiled
  DelegateAwaiterTest.cpp(277): [C2338] see reference to function template instantiation 'void `anonymous-namespace'::DoTests<1,>(FAutomationTestBase &)' being compiled
  DelegateAwaiterTest.cpp(333): [C2338] see reference to function template instantiation 'void `anonymous-namespace'::DoTests<0,>(FAutomationTestBase &)' being compiled
  utility(518): [C2794] 'type': is not a member of any direct or indirect base class of 'std::tuple_element<18446744073709551615,std::tuple<>>'
  AsyncAwaiters.h(249): [C2938] 'std::tuple_element_t' : Failed to specialize alias template

</details>

**Comment by landelare** [comment]
What's the compiler and its version?

**Comment by landelare** [comment]
What is UBT using? This line from the build output but with your numbers:

`Using Visual Studio [...] toolchain (C:\Program Files\Microsoft Visual Studio\[...]) and Windows [...] SDK.`

**Comment by landelare** [comment]
Huh. Interesting. I only saw this bug on VS2019. I refreshed the `v1.9-beta` tag, does it work for you?

**Comment by landelare** [comment]
From what I could see, the compiler attempted to resolve a template that was in an `if constexpr (something false)` block instead of ignoring it completely.

**Comment by landelare** [comment]
Thanks for the bug report!
