### ISSUE TITLE
Live coding breaks generators

### ISSUE THREAD

**Issue by qwe321** [landelare/ue5coro#14]
While some simple generators work for most of the time when rebuilding using live coding,  there are cases in which generators are broken, i.e. 

```
template <typename TItem>
class TWrappedMap
{
public:
	TMap<FString, TItem> Map;

	TGenerator<TPair<FString, TItem>> SomeGenerator()
	{
		for (const auto& Item : Map)
			co_yield TPair<FString, TItem>(Item);
	}

	TGenerator<TPair<FString, TItem>> OtherGenerator() { ... }
}
```

Rebuilding the code with live coding will result in crash where stacktrace looks like wrong method is getting called (i.e. SomeGenerator gets swapped with OtherGenerator, for SomeGenerator call stacktrace shows  OtherGenerator$_ResumeCoro$1(...), crash further points to constructor of TConstSetBitIterator breaking at range check.

**Comment by landelare** [comment]
You might be seeing the effects of this bug: https://github.com/MolecularMatters/lpp_public/issues/3
