### ISSUE TITLE
Coroutine crash when opening or leaving level in editor (game not running)

### ISSUE THREAD

**Issue by nwilson100** [landelare/ue5coro#23]
I encountered this crash while attempting to create a clean repro for a different crash I was encountering. I'm unsure if anyone would realistically encounter this specific situation, but in case it might help improve the systems, figured I would also report this.

This was tested including the recent changes in your commit 0cf2485.

Source for required class CoroExitTest attached to this issue:
[CoroEditorLevelCrash.zip](https://github.com/landelare/ue5coro/files/13829696/CoroEditorLevelCrash.zip)

Repro Case A:
1. Make empty level I'll refer to as "TestLevel".
2. Ensure the game mode is set to the blank GameModeBase.
3. Place an actor of type CoroExitTest in TestLevel.
4. Open another level in editor.
5. The editor will crash at this point.

Repro Case B:
1. Reuse the TestLevel from repro case A.
2. Start the editor.
3. Open TestLevel.
4. The editor will crash at this point.

Images here for the call stack of the crash and information about the FLatentPromise. The coro frame ptr is not available at the point of crashing, so no image of its state is provided.
![CrashPoint1](https://github.com/landelare/ue5coro/assets/20266400/3dcdcc08-7e2a-4d18-8a6c-4ef2374607a6)
![LatentPromise1](https://github.com/landelare/ue5coro/assets/20266400/460f3e83-63ef-4ff3-bdde-d8848fa117cc)

**Comment by landelare** [comment]
ACoroExitTest::BeginDestroy() is calling the coroutine when
Case A: `!IsValid(this)`
Case B: `!IsValid(GetWorld())`
Guarding against both resolves the crash in the repro case.

The issue of FLatentCoroutine being too generous with starting latent actions is exactly the same as in #22 so I'll close this one as a duplicate.
