### ISSUE TITLE
I want to keep a running coroutine alive even when the world changes.

### ISSUE THREAD

**Issue by MystIsle** [landelare/ue5coro#39]
Hello, I am an Unreal game developer who is using your coroutine plugin. This article is written using a translator, so please understand that there may be some incorrect expressions.

I am using UE5Coro version 1 for Android build. Recently, I encountered a case where coroutines are canceled when the level is changed, except when playing the game through the editor.

I checked that this version of UE5CoroSubsystem inherits UTickableWorldSubsystem. Can I change it to UGameInstanceSubsystem arbitrarily? Or is there another way to keep the coroutine alive even when the world is destroyed?

Thank you for reading.

**Comment by landelare** [comment]
This is not a support forum. Please refer to the [documentation](../blob/legacy-1.x/Docs/Async.md#execution-modes).

**Comment by MystIsle** [comment]
Thank you for your reply.
I understand your implementation keynote.
