### ISSUE TITLE
Stop or cancel coroutine

### ISSUE THREAD

**Issue by Instand** [landelare/ue5coro#5]
Hello, sorry for my question. I use your UE5Coro to learn Coroutines and UE5. I need to stop or cancel running/suspended coroutine. Is there any possibility to do that under FAsyncCoroutine? Big thanks in advance.

**Comment by landelare** [comment]
There's currently no explicit support for this, but the good news is that you don't need any!

* Latent coroutines (FLatentActionInfo parameter) are implemented as latent actions and can be canceled with built-in engine functionality (e.g., FLatentActionManager::RemoveActionsForObject).
* Async coroutines (no FLatentActionInfo) can and should be canceled cooperatively. This can be as simple as passing a bool&, TSharedPtr/std::shared_ptr&lt;std::atomic&lt;bool&gt;&gt;, or something in between depending on your multithreading needs, then co_returning early if you notice that it got flipped from the outside. This will also work for latent coroutines of course, but it doesn't match how most BP latent nodes behave.

---

Built-in support for this is a highly-requested feature that's relatively high on my list of things to implement. I want to do something more convenient than simply reinventing CancellationTokens, which is basically the shared bool pointer approach with lipstick on. Unified support for BP latent actions and "true" async makes this difficult from both an implementation complexity and a runtime performance standpoint, which is mainly why this hasn't shipped yet. I don't want to commit to a subpar implementation.

**Comment by Instand** [comment]
Thank you for answer. The second solution is not what i need really. I want something like this `FAsyncCoroutine::Cancel()`. Okay, i will try to think how implement it better for my approach and needs.
Big thanks for your time, hope you will find a better solution =)

**Comment by landelare** [comment]
This feature will ship in 1.8.
