### ISSUE TITLE
co_await Promise.GetFuture(); crash

### ISSUE THREAD

**Issue by pk1234dva** [landelare/ue5coro#9]
Hey,
the following seems to cause a crash in UE 5.0, Develop/Debug editor builds, initiated from a `UFUNCTION(CallInEditor)`
```
TPromise<int> Promise;
Promise.SetValue(123);
auto val = co_await Promise.GetFuture(); // `0xC0000005: Access violation reading location 0x0000000000000000.`
```

Not sure if I'm doing something wrong, thought I would mention it.

**Comment by landelare** [comment]
Thank you for the bug report, it will be fixed in 1.7.
